app = "wolf-discord-bot"
primary_region = "nrt"

[build]

[env]
  NODE_ENV = "production"
  LOG_LEVEL = "info"

[processes]
  app = "node dist/bot.js"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
